### ISSUE TITLE
head() method doesn't return anything

### ISSUE THREAD

**Issue by artyuum** [svyatov/CurlWrapper#9]
My code :

```
$curl = new CurlWrapper();
$response = $curl->head('https://google.com/');
echo $response;
```
Output : blank page

However, when I edit the method **setDefaultOptions()** and set **CURLOPT_HEADER** to **TRUE**, it works and it returns : 

```
HTTP/1.1 301 Moved Permanently
Location: https://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Sat, 13 May 2017 08:21:37 GMT
Expires: Mon, 12 Jun 2017 08:21:37 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 220
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
```
Is this a normal behavior ? 

Thanks.

**Comment by svyatov** [comment]
Yes, it is normal.

> The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request.

More info here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
